# Generated by Django 4.0.1 on 2022-01-26 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IMDB', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviedata',
            name='duration',
        ),
    ]
